
const emoticons = Object.freeze({


    "😬":require('../Image/emoji/emoji_1f62c.png'),
    "😷":require('../Image/emoji/emoji_1f637.png'),
    "😠":require('../Image/emoji/emoji_1f620.png'),
    "😛":require('../Image/emoji/emoji_1f61b.png'),
    "😡":require('../Image/emoji/emoji_1f621.png'),
    "😒":require('../Image/emoji/emoji_1f612.png'),
    "😏":require('../Image/emoji/emoji_1f60f.png'),
    "😣":require('../Image/emoji/emoji_1f623.png'),
    "😀":require('../Image/emoji/emoji_1f600.png'),
    "😔":require('../Image/emoji/emoji_1f614.png'),
    "😘":require('../Image/emoji/emoji_1f618.png'),
    "😍":require('../Image/emoji/emoji_1f60d.png'),
    "😟":require('../Image/emoji/emoji_1f61f.png'),
    "😧":require('../Image/emoji/emoji_1f627.png'),
    "😯":require('../Image/emoji/emoji_1f62f.png'),
    "😙":require('../Image/emoji/emoji_1f619.png'),
    "😞":require('../Image/emoji/emoji_1f61e.png'),
    "😐":require('../Image/emoji/emoji_1f610.png'),
    "😗":require('../Image/emoji/emoji_1f617.png'),
    "😕":require('../Image/emoji/emoji_1f615.png'),
    "😑":require('../Image/emoji/emoji_1f611.png'),
    "😊":require('../Image/emoji/emoji_1f60a.png'),
    "😌":require('../Image/emoji/emoji_1f60c.png'),
    "💰":require('../Image/emoji/emoji_1f4b0.png'),
    "😎":require('../Image/emoji/emoji_1f60e.png'),
    "😁":require('../Image/emoji/emoji_1f601.png'),
    "😚":require('../Image/emoji/emoji_1f61a.png'),
    "😉":require('../Image/emoji/emoji_1f609.png'),
    "😖":require('../Image/emoji/emoji_1f616.png'),
    "😴":require('../Image/emoji/emoji_1f634.png'),
    "😝":require('../Image/emoji/emoji_1f61d.png'),
    "😨":require('../Image/emoji/emoji_1f628.png'),
    "😄":require('../Image/emoji/emoji_1f604.png'),
    "😢":require('../Image/emoji/emoji_1f622.png'),
    "😥":require('../Image/emoji/emoji_1f625.png'),
    "😋":require('../Image/emoji/emoji_1f60b.png'),
    "😓":require('../Image/emoji/emoji_1f613.png'),
    "😭":require('../Image/emoji/emoji_1f62d.png'),
    "😳":require('../Image/emoji/emoji_1f633.png'),
    "😃":require('../Image/emoji/emoji_1f603.png'),
    "😪":require('../Image/emoji/emoji_1f62a.png'),
    "😵":require('../Image/emoji/emoji_1f635.png'),
    "😤":require('../Image/emoji/emoji_1f624.png'),
    "😇":require('../Image/emoji/emoji_1f607.png'),
    "😅":require('../Image/emoji/emoji_1f605.png'),
    "😈":require('../Image/emoji/emoji_1f608.png'),
    "😱":require('../Image/emoji/emoji_1f631.png'),
    "😰":require('../Image/emoji/emoji_1f630.png'),
    "😩":require('../Image/emoji/emoji_1f629.png'),
    "😂":require('../Image/emoji/emoji_1f602.png'),
    "😜":require('../Image/emoji/emoji_1f61c.png'),
    "🔞":require('../Image/emoji/emoji_1f51e.png'),
    "😫":require('../Image/emoji/emoji_1f62b.png'),
    "😆":require('../Image/emoji/emoji_1f606.png'),
    "💋":require('../Image/emoji/emoji_1f48b.png'),
    "💦":require('../Image/emoji/emoji_1f4a6.png'),
    "🌞": require('../Image/emoji/emoji_1f31e.png'),
    "👻":require('../Image/emoji/avatar.png'),
    "✈":require('../Image/emoji/emoji_2708.png'),
    "❄":require('../Image/emoji/emoji_2744.png'),
    "💏":require('../Image/emoji/emoji_1f48f.png'),
    "👏":require('../Image/emoji/emoji_1f44f.png'),
    "👍🏻":require('../Image/emoji/emoji_1f44d.png'),
    "👊🏻":require('../Image/emoji/emoji_1f44a.png'),
    "☕":require('../Image/emoji/emoji_2615.png'),
    "🎨":require('../Image/emoji/emoji_1f3a8.png'),
    "🍻":require('../Image/emoji/emoji_1f37b.png'),
    "🌻":require('../Image/emoji/emoji_1f33b.png'),
    "💐":require('../Image/emoji/emoji_1f490.png'),
    "🇺🇸":require('../Image/emoji/emoji_1f1fa_1f1f8.png'),
    "🇰🇷":require('../Image/emoji/emoji_1f1f0_1f1f7.png'),
    "🇬🇧":require('../Image/emoji/emoji_1f1ec_1f1e7.png'),
    "💅🏻":require('../Image/emoji/emoji_1f485.png'),
    "💘":require('../Image/emoji/emoji_1f498.png'),
    "👑":require('../Image/emoji/emoji_1f451.png'),
    "💖":require('../Image/emoji/emoji_1f496.png'),
    "🤔":require('../Image/emoji/emoji_1f914.png'),
    "🙄":require('../Image/emoji/emoji_1f644.png'),
    "🙂":require('../Image/emoji/emoji_1f642.png')


});


export default emoticons;
