const emoticons_value = [
    {value:"😘",url:require('../Image/emoji/emoji_1f618.png')},
    {value:"😬",url:require('../Image/emoji/emoji_1f62c.png')},
    {value:"😷",url:require('../Image/emoji/emoji_1f637.png')},
    {value:"😠",url:require('../Image/emoji/emoji_1f620.png')},
    {value:"😛",url:require('../Image/emoji/emoji_1f61b.png')},
    {value:"😡",url:require('../Image/emoji/emoji_1f621.png')},
    {value:"😒",url:require('../Image/emoji/emoji_1f612.png')},
    {value:"😏",url:require('../Image/emoji/emoji_1f60f.png')},
    {value:"😣",url:require('../Image/emoji/emoji_1f623.png')},
    {value:"😀",url:require('../Image/emoji/emoji_1f600.png')},
    {value:"😔",url:require('../Image/emoji/emoji_1f614.png')},
    {value:"😟",url:require('../Image/emoji/emoji_1f61f.png')},
    {value:"😧",url:require('../Image/emoji/emoji_1f627.png')},
    {value:"😯",url:require('../Image/emoji/emoji_1f62f.png')},
    {value:"😙",url:require('../Image/emoji/emoji_1f619.png')},
    {value:"😞",url:require('../Image/emoji/emoji_1f61e.png')},
    {value:"😐",url:require('../Image/emoji/emoji_1f610.png')},
    {value:"😗",url:require('../Image/emoji/emoji_1f617.png')},
    {value:"😕",url:require('../Image/emoji/emoji_1f615.png')},
    {value:"😑",url:require('../Image/emoji/emoji_1f611.png')},
    {value:"😊",url:require('../Image/emoji/emoji_1f60a.png')},
    {value:"😌",url:require('../Image/emoji/emoji_1f60c.png')},
    {value:"💰",url:require('../Image/emoji/emoji_1f4b0.png')},
    {value:"😎",url:require('../Image/emoji/emoji_1f60e.png')},
    {value:"😁",url:require('../Image/emoji/emoji_1f601.png')},
    {value:"😚",url:require('../Image/emoji/emoji_1f61a.png')},
    {value:"😉",url:require('../Image/emoji/emoji_1f609.png')},
    {value:"😖",url:require('../Image/emoji/emoji_1f616.png')},
    {value:"😴",url:require('../Image/emoji/emoji_1f634.png')},
    {value:"😝",url:require('../Image/emoji/emoji_1f61d.png')},
    {value:"😨",url:require('../Image/emoji/emoji_1f628.png')},
    {value:"😄",url:require('../Image/emoji/emoji_1f604.png')},
    {value:"😢",url:require('../Image/emoji/emoji_1f622.png')},
    {value:"😥",url:require('../Image/emoji/emoji_1f625.png')},
    {value:"😋",url:require('../Image/emoji/emoji_1f60b.png')},
    {value:"😓",url:require('../Image/emoji/emoji_1f613.png')},
    {value:"😭",url:require('../Image/emoji/emoji_1f62d.png')},
    {value:"😳",url:require('../Image/emoji/emoji_1f633.png')},
    {value:"😃",url:require('../Image/emoji/emoji_1f603.png')},
    {value:"😪",url:require('../Image/emoji/emoji_1f62a.png')},
    {value:"😵",url:require('../Image/emoji/emoji_1f635.png')},
    {value:"😤",url:require('../Image/emoji/emoji_1f624.png')},
    {value:"😇",url:require('../Image/emoji/emoji_1f607.png')},
    {value:"😅",url:require('../Image/emoji/emoji_1f605.png')},
    {value:"😈",url:require('../Image/emoji/emoji_1f608.png')},
    {value:"😱",url:require('../Image/emoji/emoji_1f631.png')},
    {value:"😰",url:require('../Image/emoji/emoji_1f630.png')},
    {value:"😩",url:require('../Image/emoji/emoji_1f629.png')},
    {value: "😂",url:require('../Image/emoji/emoji_1f602.png')},
    {value:"😜",url:require('../Image/emoji/emoji_1f61c.png')},
    {value:"🔞",url:require('../Image/emoji/emoji_1f51e.png')},
    {value:"😫",url:require('../Image/emoji/emoji_1f62b.png')},
    {value:"😆",url:require('../Image/emoji/emoji_1f606.png')},
    {value:"💋",url:require('../Image/emoji/emoji_1f48b.png')},
    {value:"💦",url:require('../Image/emoji/emoji_1f4a6.png')},
    {value:"🌞",url:require('../Image/emoji/emoji_1f31e.png')},
    {value:"👻",url:require('../Image/emoji/avatar.png')},
    {value:"✈",url:require('../Image/emoji/emoji_2708.png')},
    {value:"❄",url:require('../Image/emoji/emoji_2744.png')},
    {value:"💏",url:require('../Image/emoji/emoji_1f48f.png')},
    {value:"👏",url:require('../Image/emoji/emoji_1f44f.png')},
    {value:"👍🏻",url:require('../Image/emoji/emoji_1f44d.png')},
    {value:"👊🏻",url:require('../Image/emoji/emoji_1f44a.png')},
    {value: "☕",url:require('../Image/emoji/emoji_2615.png')},
    {value: "🎨",url:require('../Image/emoji/emoji_1f3a8.png')},
    {value: "🍻",url:require('../Image/emoji/emoji_1f37b.png')},
    {value: "🌻",url:require('../Image/emoji/emoji_1f33b.png')},
    {value: "💐",url:require('../Image/emoji/emoji_1f490.png')},
    {value: "🇺🇸",url:require('../Image/emoji/emoji_1f1fa_1f1f8.png')},
    {value: "🇰🇷",url:require('../Image/emoji/emoji_1f1f0_1f1f7.png')},
    {value:"🇬🇧",url:require('../Image/emoji/emoji_1f1ec_1f1e7.png')},
    {value: "💅🏻",url:require('../Image/emoji/emoji_1f485.png')},
    {value: "💘",url:require('../Image/emoji/emoji_1f498.png')},
    {value: "👑",url:require('../Image/emoji/emoji_1f451.png')},
    {value: "💖",url:require('../Image/emoji/emoji_1f496.png')},
    {value: "😍",url:require('../Image/emoji/emoji_1f60d.png')}



];

export default emoticons_value;